# Generated by Django 5.0.4 on 2024-05-01 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
